### ISSUE TITLE
Compile Error "invalid initialization of non-const reference"

### ISSUE THREAD

**Issue by vaptu** [Fytch/ProgramOptions.hxx#12]
### os:
centos 7.2

### gcc-c++: 
g++ (GCC) 4.8.5 20150623 (Red Hat 4.8.5-39)

### ProgramOptions.hxx resp current commit: 
 7ab12da5cc8f42bb710fb9e7ed26baf322a0b067
---
use `-std=c++11`  but: 

```
L112:23: error: invalid initialization of non-const reference of type ‘std::ostream& {aka std::basic_ostream<char>&}’ from an rvalue of type ‘<brace-enclosed initializer list>’
    : m_stream{ stream } {
```

**Comment by Fytch** [comment]
This seems to be a compiler issue. I was able to reproduce it with g++-4.8.5.
I pushed a workaround in commit be2fc7552eac83e766a00a4963b841d5daf3723d but from what I've seen, g++-4.8.5 is not able to handle some of the SFINAE machinery needed to get ```.bind``` working. If that is the case for you as well, I recommend you not to use ```.bind``` or upgrade to a newer compiler.

**Comment by vaptu** [comment]
thanks
