### ISSUE TITLE
iterate through all options

### ISSUE THREAD

**Issue by peterritter** [Fytch/ProgramOptions.hxx#2]
hi Josua
Good job on this library! It looks very nice and easy to use too! Thank you very much, it will save me time! 
I have a quick question for you. I need to turn all program options into a JSON object. For that I would like to iterate through all option-name:value pairs. Is there any way to do this? 
Thanks

**Comment by Fytch** [comment]
Hello, thanks for your feedback!

There is currently no way of doing that. However, I went ahead and implemented this feature. You can find the updated version here: https://gist.github.com/Fytch/aca652781803cabf28433068bf75f22c#file-programoptions-hxx-L1907-L1948
Just download the whole file and replace your local copy.

Let me know what you think. If it is fine and does what you want, I'll merge it to master.

Cheers

**Comment by peterritter** [comment]
hi josua

thanks for that, that was quick!. Can you give me two lines of code to show me how to do the iteration so I can test this? 

Thanks, Peter

**Comment by Fytch** [comment]
Quick'n'dirty:
```cpp
po::parser parser;
// set options and parse
for( auto iter = parser.begin(); iter != parser.end(); ++iter )
    if( iter->second.available() )
        std::cout << '"' << iter->first << "\": \"" << iter->second.get().string << "\"\n";
```
Note that `po::value::string` (as in `.get().string`) is always available, also for non-string types like u32.

**Comment by Fytch** [comment]
Small improvement, properly prints multi options now:
```cpp
for( auto iter = parser.begin(); iter != parser.end(); ++iter )
    if( iter->second.available() ) {
        std::cout << '"' << iter->first << "\": ";
        if( iter->second.is_single() ) {
            std::cout << '"' << iter->second.get().string << '"';
        } else {
            std::cout << "[ ";
            for( std::size_t i = 0;; ) {
                std::cout << '"' << iter->second.get( i ).string << '"';
                if( ++i == iter->second.size() )
                    break;
                std::cout << ", ";
            }
            std::cout << " ]";
        }
        std::cout << '\n';
    }
```

Cheers

**Comment by peterritter** [comment]
Hi josua
Thanks for that. I will test your class and this new functionality soon. Just give me a few days. I'm in the middle of something at the moment. Normally I don't get an answer that quickly :-)

Thanks, Peter

**Comment by peterritter** [comment]
Hi

I was just trying out this feature of being able to iterate through all options.  I do not see class parser having begin() and end() members. The above code snippets don't compile for me.
Tx,Peter

**Comment by peterritter** [comment]
oh... , was I supposed to take this from another branch?  I'm not a GIT guru. I'm still getting used to all that. Let me see if I can find your code in an alternate branch. 
P.

**Comment by peterritter** [comment]
mmh. Not sure where I would find this development branch with above feature. Please advise. 

Thanks, Peter

**Comment by Fytch** [comment]
Hey,
I'm a complete newbie when it comes to git so I uploaded a gist instead of using a branch. But now I have created a new branch for this feature: https://github.com/Fytch/ProgramOptions.hxx/tree/feature/iterate-options
Cheers

**Comment by peterritter** [comment]
Hi
Ok. The iteration seems to work. I don't intend to do a full regression test here. If I come across another issue I will raise it then. 
Thanks.
