### ISSUE TITLE
Visual c++ support

### ISSUE THREAD

**Issue by peterritter** [Fytch/ProgramOptions.hxx#4]
Hi

I develop in visual c++. I have Visual Studio 2015 .  You library is not compiling. In fact it crashes the compiler. Have you ever tested your code in Visual Studio? If so, which version are you using. The error looks like this:

1>------ Build started: Project: TS_OPTIMIZER, Configuration: Debug x64 ------
1>  opt_main.cpp
1>c:\users\ritte\_pr_dev_\dev_projects\ts_api_common\source\tsa\program_options\pr_options.h(1845): warning C4244: 'argument': conversion from '__int64' to 'int', possible loss of data
1>c:\users\ritte\_pr_dev_\dev_projects\ts_api_common\source\tsa\program_options\pr_options.h(1983): warning C4267: 'initializing': conversion from 'size_t' to 'int', possible loss of data
1>c:\users\ritte\_pr_dev_\dev_projects\ts_api_common\source\tsa\program_options\pr_options.h(1983): warning C4267: 'initializing': conversion from 'size_t' to 'const int', possible loss of data
1>c:\users\ritte\_pr_dev_\dev_projects\ts_api_common\source\tsa\program_options\pr_options.h(257): fatal error C1001: An internal error has occurred in the compiler.
1>  (compiler file 'msc1.cpp', line 1468)
1>   To work around this problem, try simplifying or changing the program near the locations listed above.
1>  Please choose the Technical Support command on the Visual C++
1>   Help menu, or open the Technical Support help file for more information
1>  c:\users\ritte\_pr_dev_\dev_projects\ts_api_common\source\tsa\program_options\pr_options.h(269): note: see reference to class template instantiation 'po::detail::make_integer_sequence_impl<std::T,3,false,false,void>' being compiled
1>          with
1>          [
1>              T=std::size_t
1>          ]
1>  c:\users\ritte\_pr_dev_\dev_projects\ts_api_common\source\tsa\program_options\pr_options.h(271): note: see reference to class template instantiation 'make_integer_sequence<std::size_t,3>' being compiled
1>  c:\users\ritte\_pr_dev_\dev_projects\ts_api_common\source\tsa\program_options\pr_options.h(510): note: see reference to class template instantiation 'make_index_sequence<3>' being compiled
1>  c:\users\ritte\_pr_dev_\dev_projects\ts_api_common\source\tsa\program_options\pr_options.h(636): note: see reference to function template instantiation 'bool po::expect<forward_iterator_t,4>(forward_iterator_t &,forward_iterator_t,const char (&)[4])' being compiled
1>          with
1>          [
1>              forward_iterator_t=std::_String_const_iterator<std::_String_val<std::_Simple_types<char>>>
1>          ]
1>  c:\users\ritte\_pr_dev_\dev_projects\ts_api_common\source\tsa\program_options\pr_options.h(680): note: see reference to function template instantiation 'po::parsing_report<po::f32_t> po::str2flt<T,std::_String_const_iterator<std::_String_val<std::_Simple_types<char>>>,void>(forward_iterator_t,forward_iterator_t)' being compiled
1>          with
1>          [
1>              T=po::f32_t,
1>              forward_iterator_t=std::_String_const_iterator<std::_String_val<std::_Simple_types<char>>>
1>          ]
1>  c:\users\ritte\_pr_dev_\dev_projects\ts_api_common\source\tsa\program_options\pr_options.h(1224): note: see reference to function template instantiation 'po::parsing_report<po::f32_t> po::str2flt<po::f32_t>(const std::string &)' being compiled
1>  INTERNAL COMPILER ERROR in 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\x86_amd64\CL.exe'
1>      Please choose the Technical Support command on the Visual C++
1>      Help menu, or open the Technical Support help file for more information
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Comment by Fytch** [comment]
I haven't tested it with MSVC because I don't use it. ProgramOptions.hxx uses C++11 and C++11-compliant compilers have no problem compiling it. I have tested it with GCC 4, 5, 6, 7, Clang 3.6, 3.7, 3.8, 3.9, 4.0 and zapcc 1.0.

That being said, I managed to reproduce your issue and I'm going to look into it!

Thanks for reporting this problem.

**Comment by Fytch** [comment]
Visual Studio 2017 seems to have no problem with ProgramOptions.hxx. You need to upgrade your compiler.

Cheers

**Comment by Fytch** [comment]
Alright, so I have figured out a workaround, if your standard library supports [C++14 `std::integer_sequence`](http://en.cppreference.com/w/cpp/utility/integer_sequence). Delete [these lines](https://github.com/Fytch/ProgramOptions.hxx/blob/master/ProgramOptions.hxx#L242-L272) and replace them by:
```cpp
	using std::integer_sequence;
	using std::make_integer_sequence;
	using std::make_index_sequence;
```
I have implemented these features myself because I wanted my library to be C++11 compatible but MSVC seems not to like my implementation.

I have tested my workaround on an online MSVC compiler of version 19.00 and it worked.

Let me know what you think!

Cheers

**Comment by Fytch** [comment]
In the meantime, I have asked in a forum why MSVC rejects the code in question and the culprit seems to have been nested class templates, which MSVC does apparently struggle with. I have downloaded Visual Studio 2015 and fixed the code in question and I'm going to push a fix to master shortly. Furthermore, I'll try to use AppVeyor MSVC CI in the future to guarantee compatibility with MSVC.

Cheers

**Comment by peterritter** [comment]
Hi
Thanks for looking into this! I'll be awaiting the latest release. It's a good thing it's a header only library! I can just copy and paste one file:-)

Peter

**Comment by Fytch** [comment]
I have noticed that MSVC complains with a lot of warnings and rightfully so. I am going to fix them tonight or tomorrow.
As you're well versed in Visual Studio, I've got a question: I set `MSBUILD_FLAGS` to `/verbosity:minimal /maxcpucount` for my AppVeyor config. Are there any other important flags? For example, I compile everything on GCC with `-Wall -Wextra`, are there similar run-of-the-mill flags for VS?

Thanks in advance and cheers

**Comment by peterritter** [comment]
hi

In terms of compiler settings, Visual Studio has a large number of them. Many are of interest to me like RTTI, optimization levels, various exception models, multithreaded libs, floating point model/exceptions, runtime checks, etc. In terms of warnings, there isn't that much. The default is Level3  (/W3), which is what I use, but there is also /W4 and  /Wall

Peter

**Comment by Fytch** [comment]
Hello Peter

Meanwhile, I managed to fully port ProgramOptions.hxx to MSVC 2015 including unit tests. [Continuous Integration is also up and running](https://ci.appveyor.com/project/Fytch/programoptions-hxx/build/13). I've also fixed most errors but callbacks sometimes still cause `warning C4244: 'argument': conversion from 'const po::i64_t' to 'po::f64_t', possible loss of data `.

Cheers

**Comment by peterritter** [comment]
hi
Thanks for that. I hope I didn't ruin your weekend plans. I'll let you know once I've tried it out.

Thanks, Peter

**Comment by peterritter** [comment]
Hi
Ok, I have included the latest ProgramOptions.h header. The program now compiles and seems to work under Visual Studion 2015. Thanks for the fix!! I will report other errors if any should arise. 
Thanks, Peter
